version: 2.1

jobs:
  trigger_build:
    docker:
      - image: alpine:3.15.0
    resource_class: small
    steps:
      - run:
          name: Install curl
          command: |
            apk update && \
            apk upgrade
            apk add curl
      - run:
          name: Trigger build for infra repo
          command: |
            curl --request POST \
            --url https://circleci.com/api/v2/project/gh/Vladyslav-Stepanenko/circle-ci-builds/pipeline \
            --header "Circle-Token: $API_TOKEN" \
            --header "content-type: application/json"
workflows:
  trigger_ami_build:
    jobs:
      - trigger_build
