version: 2.1

jobs:
  trigger_build:
    docker:
      - image: alpine:3.15.0
    resource_class: small
    steps:
      - run:
          name: Install curl
          command: |
            apk update && \
            apk upgrade
            apk add curl
      - run:
          name: Trigger build for infra repo
          command: |
            curl --location --request POST 'https://circleci.com/api/v2/project/github/Vladyslav-Stepanenko/nginx-test/pipeline' \
            --header 'Content-Type: application/json' \
            -u "${API_TOKEN}"

workflows:
  trigger_ami_build:
    jobs:
      - trigger_build
